FROM registry.access.redhat.com/ubi9/nodejs-20:latest AS builder

USER root
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

FROM registry.access.redhat.com/ubi8/nginx-120:latest

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
